version: '2'
services:

  # application (code)
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /app
    volumes:
      - ${PROJECT_DIR}:/app
    networks:
      - studio
    environment:
      - DB_PORT=5432
      - DB_HOST=database

  cron:
    build:
      context: ./
      dockerfile: cron.dockerfile
    networks:
      - studio


  # http server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /app
    networks:
      - studio
    volumes_from:
      - app
    ports:
      - 666:80

  # database
  database:
    image: postgres:10.1
    networks:
      - studio
    environment:
      - POSTGRES_DB=studio
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 54326:5432

  # adminer
  adminer:
    image: adminer
    networks:
      - studio
    ports:
      - 8888:8080

  #portainer:
    #image: portainer/portainer
    #networks:
      #- studio
    #volumes:
      #- /var/run/docker.sock:/var/run/docker.sock
    #ports:
      #- 600:9000

  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_EXTRA_FLAGS=--maxmemory 100mb
    networks:
      - studio


networks:
  studio:
    driver: "bridge"
